#!/bin/bash

if ! cliclick $(yabai -m query --windows --window | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"'); then
    DISPLAYS=$(yabai -m query --displays)
    NUM_DISPLAYS=$(echo "$DISPLAYS" | jq length)
    CURRENT_DISPLAY=$(echo "$DISPLAYS" | jq -r '.[] | select(.["has-focus"] == true) | .uuid')
    if [[ $NUM_DISPLAYS -eq 1 ]]; then
        cliclick m:900,603
    elif [[ $CURRENT_DISPLAY == "37D8832A-2D66-02CA-B9F7-8F30A301B230" ]]; then
        cliclick m:3460,603
    else
        cliclick m:1280,720
    fi
fi
