#!/bin/bash

yabai -m space --create
INDEX="$(yabai -m query --spaces --display | jq 'map(select(.["is-native-fullscreen"] == false))[-1].index')"
yabai -m space --focus "${INDEX}"
sleep 0.01
skhd -k "fn - x"
sleep 0.1
sketchybar --update
