#!/bin/bash

if [ "$(/opt/homebrew/bin/yabai -m query --displays | /opt/homebrew/bin/jq -r '.[0]."uuid"')" = "37D8832A-2D66-02CA-B9F7-8F30A301B230" ]; then
    /opt/homebrew/bin/SwitchAudioSource -s "MacBook Pro Speakers" &> /dev/null
else
    /opt/homebrew/bin/SwitchAudioSource -s "SoundID Reference" &> /dev/null
fi
sleep 1
sudo killall coreaudiod
sleep 1
/opt/homebrew/bin/yabai --restart-service
/opt/homebrew/bin/sketchybar --reload
