#!/bin/bash

sleep 3.7
killall "LogiTune" &> /dev/null
# /Users/q/.config/sketchybar/.clock &
sleep 3.7
/opt/homebrew/bin/sketchybar --reload
sleep 0.73 # 13.7 # Karabiner Update Agent is done also after this time - for sure it seems. 
    # ---> back to 3.7-no: 0,73 because karabiner always takes longer.. just "manually" wait till karabiner updater is done..
/Users/q/bin/cliclick_focus
/opt/homebrew/bin/cliclick c:. # to "remove" iTerm focus

# /Users/*/Library/LaunchAgents/com.*.custom_start.plist
#
# <?xml version="1.0" encoding="UTF-8"?>
# <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
# <plist version="1.0">
# <dict>
#     <key>Label</key>
#     <string>com.q.custom_start</string>
#     <key>ProgramArguments</key>
#     <array>
#         <string>/Users/q/bin/custom_start</string>
#     </array>
#     <key>RunAtLoad</key>
#     <true/>
#     <key>StandardOutPath</key>
#     <string>/tmp/custom_start.log</string>
#     <key>StandardErrorPath</key>
#     <string>/tmp/custom_start_error.log</string>
# </dict>
# </plist>
