#!/bin/bash

# exec 200>/tmp/custom_wake.lock
# flock -n 200 || exit 0

/opt/homebrew/bin/sketchybar --set audio drawing=off
if [ "$(/opt/homebrew/bin/yabai -m query --displays | /opt/homebrew/bin/jq -r '.[0]."uuid"')" = "37D8832A-2D66-02CA-B9F7-8F30A301B230" ]; then
    /opt/homebrew/bin/SwitchAudioSource -s "MacBook Pro Speakers" &> /dev/null
    sleep 1
    osascript -e "set volume output volume 50"
else
    killall "SoundID Reference" &> /dev/null
    sleep 0.1
    open -a "SoundID Reference" &> /dev/null
    sleep 3.7
    # /opt/homebrew/bin/SwitchAudioSource -s "SoundID Reference" &> /dev/null
    /Users/q/bin/open_or_focus "SoundID Reference"
    sleep 0.1
    /Users/q/bin/close_soundid
    sleep 1
    /opt/homebrew/bin/sendmidi dev "IAC Driver SID" cc 1 1
    sleep 0.37
    /opt/homebrew/bin/sendmidi dev "IAC Driver SID" cc 0 127
    sleep 1
    osascript -e "set volume output volume 100"
fi
sleep 0.17
if [[ "$(/opt/homebrew/bin/SwitchAudioSource -c)" == "SoundID Reference" ]]; then
    /opt/homebrew/bin/skhd -k "shift + alt - f16"
fi
sleep 0.1
sudo killall coreaudiod # # # what's systemsoundserverd doing?
sleep 2.1
/opt/homebrew/bin/yabai --restart-service
sleep 3.7
/opt/homebrew/bin/sketchybar --reload
