#!/bin/bash

trap 'yabai -m config mouse_follows_focus off' EXIT
SPACES=$(yabai -m query --spaces)
CURRENT_SPACE_INDEX=$(echo "$SPACES" | jq '.[] | select(."has-focus") | .index')
FULLSCREENS=$(echo "$SPACES" | jq '[.[] | select(."is-native-fullscreen")]')
if [[ -z "$FULLSCREENS" || "$(echo "$FULLSCREENS" | jq 'length')" -eq 0 ]]; then
    echo "$SPACES" | jq -r '.[] | select(.windows == []) | .index' | sort -nr | xargs -I {} yabai -m space {} --destroy
    sleep 0.1
    sketchybar --update
    exit 1
fi
NEXT_FULLSCREEN_INDEX=$(echo "$FULLSCREENS" | jq --argjson current "$CURRENT_SPACE_INDEX" 'map(select(.index > $current))[0].index // map(.index)[0]')
if [[ -z "$NEXT_FULLSCREEN_INDEX" || "$NEXT_FULLSCREEN_INDEX" == "null" ]]; then
    exit 1
fi
# yabai -m config mouse_follows_focus on
{ yabai -m space --focus "$NEXT_FULLSCREEN_INDEX" && cliclick $(yabai -m query --windows --window | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"'); } || exit 1
