#!/bin/bash

if [[ "$(/opt/homebrew/bin/mac-brightnessctl | awk '{print $NF}')" == "0.37" ]]; then # 0.49 # 0.00
    /opt/homebrew/bin/mac-brightnessctl 0.00 # 0.49 # 0.37
else
    /opt/homebrew/bin/mac-brightnessctl 0.37 # 0.49 # 0.00
fi
