#!/bin/bash

[[ "$(yabai -m query --spaces --space | jq '.["is-native-fullscreen"]')" == "false" ]]
yabai -m space --create
index="$(yabai -m query --spaces --display | jq 'map(select(.["is-native-fullscreen"] == false))[-1].index')"
yabai -m window --space "${index}"
yabai -m space --focus "${index}"
yabai -m window --focus mouse && cliclick $(yabai -m query --windows --window | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"')
sleep 0.1
sketchybar --update
