#!/bin/bash

yabai -m window --display prev --focus
sleep 0.1
yabai -m window --grid 1:1:0:0:1:1
cliclick $(yabai -m query --windows --window | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"')
