#!/bin/bash

yabai -m window --focus mouse
yabai -m config mouse_follows_focus on # alttab
yabai -m config mouse_modifier fn
cliclick m:+0,+39
cliclick m:+0,-39
yabai -m config mouse_modifier ctrl
open -a "$1"
# eval $(yabai -m query --windows --window | jq -r '.frame | "cliclick m:\(.x + .w/2 | floor),\(.y + .h/2 | floor)"')
# sleep 0.1
sleep 0.37
eval $(yabai -m query --windows --window | jq -r '.frame | "cliclick m:\(.x + .w/2 | floor),\(.y + .h/2 | floor)"')
# open -a "$1"
yabai -m config mouse_follows_focus off # alttab
