#!/bin/bash

osascript -e 'tell application "Finder" to make new Finder window to (POSIX file "'"$1"'")'
open $1
sleep 0.01
cliclick $(yabai -m query --windows --window | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"')
