#!/bin/bash

WINDOWS_WINDOW=$(yabai -m query --windows --window)
DISPLAYS=$(yabai -m query --displays)
NUM_DISPLAYS=$(echo "$DISPLAYS" | jq length)
# CURRENT_DISPLAY=$(yabai -m query --displays --window | jq -r '.uuid')
CURRENT_DISPLAY=$(echo "$DISPLAYS" | jq -r '.[] | select(.["has-focus"] == true) | .uuid')
UUID_INBUILT_DISPLAY="37D8832A-2D66-02CA-B9F7-8F30A301B230"
CURRENT_APP=$(echo "$WINDOWS_WINDOW" | jq -r '.app')
CURRENT_APP_ALT=$(sketchybar --query front_app | jq -r '.icon.value')
case "$CURRENT_APP_ALT" in
    "Finder") skhd -k "cmd - w" ;;
    "LogiTune") 
        sketchybar --set logi icon.color=0xff4e4e4e
        osascript -e 'tell application "Logi Tune" to quit'
        sketchybar --update
        CURRENT_DISPLAY="$UUID_INBUILT_DISPLAY"
        ;;
    "Threema Beta") killall ThreemaDesktop &> /dev/null ;;
    "Thunderbird") 
        killall thunderbird &> /dev/null
        sleep 0.1
        ~/.config/sketchybar/plugins/badge.sh
        ;;
    "OBS Studio") osascript -e 'tell application "OBS" to quit' ;;
    "TotalMix FX") 
        osascript -e 'tell application "TotalMix FX" to quit'
        yabai -m window --focus mouse
        exit
        ;;
    "zoom.us") killall zoom.us ;;
    "LibreOffice") osascript -e 'tell application "LibreOffice" to quit' ;;
    *) 
        if [[ "$CURRENT_APP" == *WhatsApp* ]]; then
            killall WhatsApp &> /dev/null
        else
            skhd -k "cmd - q"
        fi
        ;;
esac
sleep 0.37
if [[ $NUM_DISPLAYS -eq 1 ]]; then
    cliclick m:900,603
elif [[ $CURRENT_DISPLAY == "$UUID_INBUILT_DISPLAY" ]]; then
    cliclick m:3460,603
else
    cliclick m:1280,720
fi
# CURRENT_APP=$(yabai -m query --windows --window | jq -r '.app')
# CURRENT_APP_ALT=$(sketchybar --query front_app | jq -r '.icon.value')
# CURRENT_DISPLAY=$(yabai -m query --displays --window | jq -r '."uuid"')
# if [[ "$CURRENT_APP" == *WhatsApp* ]]; then
#     killall WhatsApp &> /dev/null
# elif [[ "$CURRENT_APP_ALT" == "Finder" ]]; then
#     skhd -k "cmd - w"
# elif [[ "$CURRENT_APP_ALT" == "LogiTune" ]]; then
#     sketchybar --set logi icon.color=0xff4e4e4e
#     osascript -e 'tell application "Logi Tune" to quit'
#     sketchybar --update
#     CURRENT_DISPLAY="37D8832A-2D66-02CA-B9F7-8F30A301B230"
# elif [[ "$CURRENT_APP_ALT" == "Threema Beta" ]]; then
#     killall ThreemaDesktop &> /dev/null
# elif [[ "$CURRENT_APP_ALT" == "Thunderbird" ]]; then
#     killall thunderbird &> /dev/null
#     sleep 0.1
#     ~/.config/sketchybar/plugins/badge.sh
# elif [[ "$CURRENT_APP_ALT" == "OBS Studio" ]]; then
#     osascript -e 'tell application "OBS" to quit'
# elif [[ "$CURRENT_APP_ALT" == "TotalMix FX" ]]; then
#     osascript -e 'tell application "TotalMix FX" to quit'
#     yabai -m window --focus mouse
#     exit
# elif [[ "$CURRENT_APP_ALT" == "zoom.us" ]]; then
#     killall zoom.us
# elif [[ "$CURRENT_APP_ALT" == "LibreOffice" ]]; then
#     osascript -e "tell application \"LibreOffice\" to quit"
# else
#     skhd -k "cmd - q"
# fi
# sleep 0.37
# DISPLAYS=$(yabai -m query --displays)
# NUM_DISPLAYS=$(echo "$DISPLAYS" | jq length)
# CURRENT_DISPLAY=$(yabai -m query --displays --display | jq -r '.uuid')
# UUID_INBUILT_DISPLAY="37D8832A-2D66-02CA-B9F7-8F30A301B230"
# if [[ $NUM_DISPLAYS -eq 1 ]]; then
#     cliclick m:900,603
# elif [[ $CURRENT_DISPLAY == "$UUID_INBUILT_DISPLAY" ]]; then
#     cliclick m:3460,603
# else
#     cliclick m:1280,720
# fi
## if [[ $CURRENT_DISPLAY == "37D8832A-2D66-02CA-B9F7-8F30A301B230" ]]; then
##     cliclick m:3460,603 # (+19)
## else
##     cliclick m:1280,720
## fi
sleep 0.01
yabai -m window --focus mouse || (cliclick c:. && osascript -e 'tell application "System Events" to set visible of every process whose visible is false to true')
sleep 0.01
skhd -k "fn - x"
sleep 0.1
sketchybar --update
