#!/bin/bash

CURRENT_APP=$(yabai -m query --windows --window | jq -r '.app')
CURRENT_APP_ALT=$(sketchybar --query front_app | jq -r '.icon.value')
# CLEANED_APP="${CURRENT_APP// /}"
# CLEANED_APP_ALT="${CURRENT_APP_ALT// /}"
yabai -m window --focus mouse || cliclick $(yabai -m query --displays --display | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"')
CURRENT_DISPLAY=$(yabai -m query --displays --display | jq '.index')
# CURRENT_DISPLAY=$(yabai -m query --displays | jq '.[] | select(.["has-focus"] == true) | .index')
# # # # # # # # #=$(echo $WINDOWS_WINDOW | jq -r '.display')
if [[ "$CURRENT_APP" == *WhatsApp* ]]; then
    killall WhatsApp &> /dev/null
elif [[ "$CURRENT_APP_ALT" == "Finder" ]]; then
    skhd -k "cmd - w"
elif [[ "$CURRENT_APP_ALT" == "LogiTune" ]]; then
    sketchybar --set logi icon.color=0xff4e4e4e
    osascript -e 'tell application "Logi Tune" to quit'
    sketchybar --update # ~/.config/sketchybar/plugins/logi.sh
elif [[ "$CURRENT_APP_ALT" == "Threema Beta" ]]; then
    killall ThreemaDesktop &> /dev/null
elif [[ "$CURRENT_APP_ALT" == "Thunderbird" ]]; then
    killall thunderbird &> /dev/null
    sleep 0.1
    ~/.config/sketchybar/plugins/badge.sh
elif [[ "$CURRENT_APP_ALT" == "OBS Studio" ]]; then
    osascript -e 'tell application "OBS" to quit'
elif [[ "$CURRENT_APP_ALT" == "TotalMix FX" ]]; then
    osascript -e 'tell application "TotalMix FX" to quit'
    yabai -m window --focus mouse
    exit
elif [[ "$CURRENT_APP_ALT" == "zoom.us" ]]; then
    killall zoom.us
else
    skhd -k "cmd - q"
fi
sleep 0.37
yabai -m display --focus $CURRENT_DISPLAY
sleep 0.1
yabai -m window --focus mouse || cliclick c:+0,+0
cliclick $(yabai -m query --windows --window 2>/dev/null | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"' 2>/dev/null) || cliclick $(yabai -m query --displays --display | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"')
sleep 0.1
sketchybar --update
