#!/bin/bash

skhd -k "hyper - d"
sleep 0.37
# cliclick_focus || {
yabai -m window --focus mouse || {
    DISPLAYS=$(yabai -m query --displays)
    NUM_DISPLAYS=$(echo "$DISPLAYS" | jq length)
    CURRENT_DISPLAY=$(echo "$DISPLAYS" | jq -r '.[] | select(.["has-focus"] == true) | .uuid')
    sleep 0.21 # 0.37
    if [[ $NUM_DISPLAYS -eq 1 ]]; then
        cliclick c:900,603
    elif [[ $CURRENT_DISPLAY == "37D8832A-2D66-02CA-B9F7-8F30A301B230" ]]; then
        cliclick c:3460,603
    else
        cliclick c:1280,720
    fi
}
