#!/bin/bash

rsync -a /Users/q/.zprofile /Users/q/.config/zsh_configs/
rsync -a /Users/q/.zshrc /Users/q/.config/zsh_configs/

# ------- #

rsync -a /Users/q/bin/SYNC /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/brewup /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/custom_start /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/custom_wake /Users/q/.config/bin_scripts/

rsync -a /Users/q/bin/display_query_cliclick /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/cliclick_focus /Users/q/.config/bin_scripts/

rsync -a /Users/q/bin/open_or_focus /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/open_folder /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/quit_script /Users/q/.config/bin_scripts/

rsync -a /Users/q/bin/change_and_focus_display /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/move_current_window_to_previous_display /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/move_current_window_to_next_display /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/cycle_fullscreens_or_del_empty_spaces /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/yabai_prev_space_on_display /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/yabai_next_space_on_display /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/create_and_focus_new_space /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/move_current_window_to_new_space_and_focus /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/del_empty_spaces /Users/q/.config/bin_scripts/

rsync -a /Users/q/bin/yabaitoggle /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/toggle_brightness /Users/q/.config/bin_scripts/

rsync -a /Users/q/bin/threema_start /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/thunderbird_badge /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/tmx_hotkey /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/foobar_play /Users/q/.config/bin_scripts/

rsync -a /Users/q/bin/mouse_dock /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/show_desktop /Users/q/.config/bin_scripts/

rsync -a /Users/q/bin/volume_down /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/volume_up /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/brightness_down /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/brightness_up /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/close_soundid /Users/q/.config/bin_scripts/

rsync -a /Users/q/bin/macos_background_noise /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/radio /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/keyboard_backlight /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/yabai_debug /Users/q/.config/bin_scripts/

# ------- #

rsync -a /Users/q/bin/quit_all_apps.scpt /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/paste_time_n_date.scpt /Users/q/.config/bin_scripts/
rsync -a /Users/q/bin/paste_shortened_url.scpt /Users/q/.config/bin_scripts/
