#!/bin/bash

boq=$(pgrep -x thunderbird)
if [ -z "$boq" ]; then
    sketchybar --set front_app icon.color=0xff4e4e4e
    yabai -m display --focus first
    sleep 0.1
    skhd -k "alt + cmd - w"
    sleep 0.1
    open_or_focus "thunderbird"
    sleep 2
    ~/.config/sketchybar/plugins/badge.sh
    sketchybar --set front_app icon.color=0xffc7c7c7
else
    open_or_focus "thunderbird"
fi
