#!/bin/bash

BOQ=$(pgrep -x thunderbird)
if [ -z "$BOQ" ]; then
    sketchybar --set front_app icon.color=0xff4e4e4e
    yabai -m display --focus first
    sleep 0.1
    create_and_focus_new_space
    sleep 0.1
    open_or_focus "thunderbird"
    sleep 2
    ~/.config/sketchybar/plugins/badge.sh
    del_empty_spaces
    sketchybar --set front_app icon.color=0xffc7c7c7
else
    open_or_focus "thunderbird"
fi
