#!/bin/bash

BOQ=$(pgrep -x thunderbird)
if [ -z "$BOQ" ]; then
    sketchybar --set front_app icon.color=0xff4e4e4e
    yabai -m display --focus first
    sleep 0.1
    yabai -m space --create # changed from using create_and_focus_new_space because if ctrl is held down still, cliclick c:. will open context menu; but still: if ctrl is held, thunderbird is buggy: doesn't show emails..
    yabai -m space --focus "$(yabai -m query --spaces --display | jq 'map(select(.["is-native-fullscreen"] == false))[-1].index')"
    sleep 0.1
    open_or_focus "thunderbird"
    # open -a "thunderbird"
    # sleep 0.73
    # cliclick_focus
    # sleep 1

    sleep 0.37
    killall "thunderbird"
    sleep 1.37 # 0.1
    open_or_focus "thunderbird"

    sleep 2
    ~/.config/sketchybar/plugins/badge.sh
    del_empty_spaces
    sketchybar --set front_app icon.color=0xffc7c7c7
else
    yabai -m space --focus "$(yabai -m query --windows | jq -r 'map(select(.app == "Thunderbird")) | sort_by(.frame.w * .frame.h) | reverse | .[0].space')"
    # yabai -m query --windows | jq '.[] | select(.app=="Thunderbird") | .space' | head -n1
    open_or_focus "thunderbird"
fi
