#!/bin/bash

tmx_hotkey() {
    local KEY_COMMAND=$1
    local POS
    POS=$(cliclick p)
    open -a "Totalmix"
    sleep 0.73
    open_or_focus "Totalmix"
    skhd -k "$KEY_COMMAND"
    skhd -k "cmd - q"
    cliclick m:$POS
    yabai -m window --focus mouse
}
tmx_hotkey "$1"
