#!/bin/bash

if [ "$($1)" = "on" ]; then
    $1 off
elif [ "$($1)" = "off" ]; then
    $1 on
elif [ "$($1)" = "1.0000" ]; then
    $1 0.0000
    # /Users/q/bin/cliclick_focus
else
    $1 1.0000
    /opt/homebrew/bin/cliclick m:$(yabai -m query --displays | jq -r '.[] | select(.["has-focus"] == true) | "\((.frame.x + .frame.w - 137) | floor),\((.frame.y) | floor)"'); sleep 0.37; cliclick c:.
fi
