#!/bin/bash

# /opt/homebrew/bin/yabai -m query --windows --window > ~/Desktop/yabai_debug.txt #.../enter = 0x4C: keysmith : yabai_debugging [pent_to_fn_enter]
# yabai -m query --windows --window | jq '."frame"."y"' > ~/Desktop/yabai_debug.txt
# yabai -m query --windows --window
# COM=$(yabai -m query --windows --space | jq --arg app "$(yabai -m query --windows --window | jq -r '.app')" '[.[] | select(.app == $app) | .id]')
# COM=$(yabai -m query --windows --space | jq -r --arg app "$(yabai -m query --windows --window | jq -r '.app')" '[.[] | select(.app == $app) | .id] | last')
# COM=$(yabai -m query --windows --window | jq -r '.app')
# COM=$(yabai -m query --windows --space)
# COM=$(yabai -m space --create)
# echo "$COM" > ~/Desktop/yabai_debug.txt

# COM=$(yabai -m space --create)
# bash -x { yabai -m window --grid 1:2:1:1:1:2; sleep 0.01; ~/bin/cliclick_focus } > ~/Desktop/yabai_debug.txt 2>&1 # echo $focus_next_window > ~/Desktop/yabai_debug.txt
# bash -x -c "yabai -m window --grid 1:2:1:1:1:2; sleep 0.01; $HOME/bin/cliclick_focus" > "$HOME/Desktop/yabai_debug.txt" 2>&1
# exec > "$HOME/Desktop/yabai_debug.txt" 2>&1
# set -x
# yabai -m window --grid 1:2:1:1:1:2
# sleep 0.01
# "$HOME/bin/cliclick_focus"
# yabai -m query --windows --window 2>&1 > ~/Desktop/yabai_debug.txt
# /opt/homebrew/bin/skhd -k 'ctrl + cmd - y' 2>&1 > ~/Desktop/yabai_debug.txt
