#!/bin/bash

if [ "$($1)" = "on" ]; then
    $1 off
elif [ "$($1)" = "off" ]; then
    $1 on
elif [ "$($1)" = "1.0000" ]; then
    $1 0.0000
else
    $1 1.0000
    /opt/homebrew/bin/cliclick m:$(yabai -m query --displays | jq -r '.[] | select(.["has-focus"] == true) | "\((.frame.x + .frame.w - 49) | floor),\((.frame.y) | floor)"')
fi
