#!/bin/bash

if [ -f /tmp/mission_control.open ]; then
    skhd -k "hyper - 0x12"
else
    SPASPA=$(yabai -m query --spaces --space)
    CURDIS=$(yabai -m query --displays --display | jq '.index')
    CURSPA=$(echo "$SPASPA" | jq '.index')
    SPACES=$(yabai -m query --spaces --display "$CURDIS")
    ALLSPA=$(echo "$SPACES" | jq ".[].index")
    LOWSPA=$(echo "$SPACES" | jq ".[] | select(.index < $CURSPA) | .index")
    if [ ! -z "$LOWSPA" ]; then
        set -- $LOWSPA
        yabai -m space --focus ${@: -1}
    else
        set -- $ALLSPA
        yabai -m space --focus ${@: -1}
    fi
    # del_empty_spaces
    # sleep 0.1
    # ~/bin/cliclick_focus
fi
