#!/bin/bash

SPASPA=$(yabai -m query --spaces --space)
CURDIS=$(yabai -m query --displays --display | jq '.index')
CURSPA=$(echo "$SPASPA" | jq '.index')
SPACES=$(yabai -m query --spaces --display "$CURDIS")
ALLSPA=$(echo "$SPACES" | jq ".[].index")
HIGSPA=$(echo "$SPACES" | jq ".[] | select(.index > $CURSPA) | .index")
if [ ! -z "$HIGSPA" ]; then
    set -- $HIGSPA
    yabai -m space --focus $1
else
    set -- $ALLSPA
    yabai -m space --focus $1
fi
del_empty_spaces
sleep 0.01
cliclick $(yabai -m query --windows --window | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"') || cliclick $(yabai -m query --displays --display | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"')
