#!/bin/bash

# /opt/homebrew/bin/yabai -m query --windows --window > ~/Desktop/yabai_debug.txt #.../enter = 0x4C: keysmith : yabai_debugging [pent_to_fn_enter]
# yabai -m query --windows --window | jq '."frame"."y"' > ~/Desktop/yabai_debug.txt
COM=$(yabai -m query --windows --window)
echo "$COM" > ~/Desktop/yabai_debug.txt
