#!/bin/bash

SPASPA=$(yabai -m query --spaces --space)
CURDIS=$(yabai -m query --displays --display | jq '.index')
CURSPA=$(echo "$SPASPA" | jq '.index')
SPACES=$(yabai -m query --spaces --display "$CURDIS")
ALLSPA=$(echo "$SPACES" | jq ".[].index")
LOWSPA=$(echo "$SPACES" | jq ".[] | select(.index < $CURSPA) | .index")
if [ ! -z "$LOWSPA" ]; then
    set -- $LOWSPA
    yabai -m space --focus ${@: -1}
else
    set -- $ALLSPA
    yabai -m space --focus ${@: -1}
fi
del_empty_spaces
# sleep 0.1
yabai -m window --focus mouse || cliclick c:+0,+0
cliclick $(yabai -m query --windows --window 2>/dev/null | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"' 2>/dev/null) || cliclick $(yabai -m query --displays --display | jq -r '.frame | "m:\(.x + (.w/2) | floor),\(.y + (.h/2) | floor)"')
